### ISSUE TITLE
incorrect path to JS vendor folder

### ISSUE THREAD

**Issue by jordonrupp** [ahmadawais/WPGulpTheme#4]
The path to the JS vendor folder is named "vendor" in gulpfile.js but the directory is named "vendors"

**Comment by ahmadawais** [comment]
I just pushed a huge update. 

> Make sure you realize that this repository is just an implementation of [WPGulp](https://github.com/ahmadawais/WPGulp. So, you should use [WPGulp](https://github.com/ahmadawais/WPGulp) repository for your production themes and plugins.

**Comment by ahmadawais** [comment]
Also read the new ReadMe file :)

**Comment by jordonrupp** [comment]
Thank you!  I'm using the WPGulp repo for projects now.  I thought that edit would be helpful to others just getting started.  Excellent work and much-appreciated toolkit!

**Comment by ahmadawais** [comment]
Glad you liked it. Thanks for reporting :)

Also, do signup for the video series link in the readme :)
