### ISSUE TITLE
Question regarding vendor.js and vendor2.js

### ISSUE THREAD

**Issue by amichel86** [ahmadawais/WPGulpTheme#8]
Hey man, thanks for this workflow. I was looking around this morning and find yours, decided to give it a try. I just had a quick question.

Let's say I need to use a jQuery slider plugin is there a way to import it in "vendor.js" or I should copy/paste the code there from the plugin itself? What Is the use of "vendor2.js" exactly?

It'd be nice if when saving a PHP file only the front-end portion is getting refreshed and not the backend. :)

Last thing, when adding a new .scss file we need to restart Gulp in order for this file to be present. It would be cool if this step wouldn't necessary.

Thank you so much and keep up the good work!

**Comment by ahmadawais** [comment]
@amichel86 Thanks for the kind words.

All of that is good to have. And is possible. 

This is a dummy project the original repo is https://github.com/ahmadawais/WPGulp

Also we have a new version 2.0.0 almost ready. Try that out https://github.com/ahmadawais/WPGulp/tree/v2.0.0 and contribute or create an issue on that repo after testing the new branch. 

Peace ✌️

**Comment by amichel86** [comment]
Awesome, thanks man! :)

**Comment by amichel86** [comment]
Awesome, in your V2 is it normal you talk about Project Variables but there is no variables to change in the new Gulpfile?

**Comment by ahmadawais** [comment]
Actually in v2.0.0 all the variables are now moved to a config.js file
(name not final yet). And this makes gulpfile.js easily updateable. Sadly,
docs are not ready yet.





*  AHMAD AWAIS  *
  Full Stack Web Developer — Regular WordPress Core Contributor/Dev

*AhmadAwais.com
<https://ahmadawais.com/?utm_source=email_signature&utm_medium=email>** |
Say Hi on Twitter <https://twitter.com/mrahmadawais/>* *| **Facebook
<https://fb.com/ahmadawais/> **| **GitHub <https://github.com/ahmadawais> *
*| **WordPress <https://profiles.wordpress.org/mrahmadawais/> **|* *LinkedIn
<http://pk.linkedin.com/in/mrahmadawais>*
 *Skype/Slack: MrAhmadAwais *
