### ISSUE TITLE
Slow at reloading (working alongside Local by Flywheel)

### ISSUE THREAD

**Issue by lukereech** [ahmadawais/WPGulpTheme#9]
So I'm running/building my WordPress sites with Local by Flywheel[https://local.getflywheel.com] which creates a local domain which I then use as the proxy with this gulp workflow. 

My problem is the site is so slow at local, I can complete a style change and I get a notification it has completed but the page takes a good 5 sessions to then load after, the status bar at the bottom just says 'Waiting for localhost'

Any ideas?

**Comment by ahmadawais** [comment]
Try commenting the line that watches for PHP files. It can slow things down for slow systems. Otherwise, there's nothing more to it.

**Comment by lukereech** [comment]
Hey Ahmad, tried that and still nothing, I run gulp and it opens the new browser tab and sits at this for around 5-7seconds. Likewise when doing a CSS edit, it isn't instant and takes around the same time. Is there anything else at all that could cause this?

![screen shot 2018-04-10 at 11 18 58](https://user-images.githubusercontent.com/37796997/38551443-11aa2b8c-3cb1-11e8-9bcf-b4bc123cb7a1.png)

**Comment by ahmadawais** [comment]
Not sure. I also use Local and it's been a bit slow lately. But not that slow. I will investigate and let you know.

BTW Checkout the v2.0.0 branch of upcoming WPGulp which has a separate config file and updated modern JavaScript based workflow. Might fix the issue.

**Comment by lukereech** [comment]
No problem, do let me know if you need anything off me that can assist!

Will do, thank you!

**Comment by lspoor** [comment]
Just wondering if there are any updates on this?

FYI I posted this on the wrong repo, it was supposed to be on https://github.com/ahmadawais/WPGulp

But regardless I'm still experiencing this issue and an without any browsersync functionality.

**Comment by lukereech** [comment]
Just wondering if there are any updates on this?

FYI I posted this on the wrong repo, it was supposed to be on https://github.com/ahmadawais/WPGulp

But regardless I'm still experiencing this issue and an without any browsersync functionality

**Comment by ahmadawais** [comment]
This is a dummy repo. Use WPGulp instead.
